version: '3'
services:
  web:
    image: python:3.9-slim
    container_name: my-python-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: python app.py
    ports:
      - "5000:5000"
